version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_DB: comida_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Atilas123*
    expose:
      - 5432
    #ports:
    #  - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.dlgServ-prefix.stripprefix.prefixes=/comeserver"
      - "traefik.http.routers.dlgServ.middlewares=dlgServ-prefix"
      - "traefik.http.routers.dlgServ.rule=Host(`variedades-jireh.ddns.net`) && PathPrefix(`/comeserver`)"
      - "traefik.http.routers.dlgServ.entrypoints=websecure" # changed
      - "traefik.http.routers.dlgServ.tls=true"
      - "traefik.http.routers.dlgServ.tls.certresolver=lets-encrypt" # new
      - "traefik.http.services.dlgServ.loadbalancer.server.port=5432"    

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: eddy9062@test.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    expose:
      - 80
    #ports:
    #  - "8080:80"

    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.dlgServ-prefix.stripprefix.prefixes=/pga"
      - "traefik.http.routers.dlgServ.middlewares=dlgServ-prefix"
      - "traefik.http.routers.dlgServ.rule=Host(`variedades-jireh.ddns.net`) && PathPrefix(`/pga`)"
      - "traefik.http.routers.dlgServ.entrypoints=websecure" # changed
      - "traefik.http.routers.dlgServ.tls=true"
      - "traefik.http.routers.dlgServ.tls.certresolver=lets-encrypt" # new
      - "traefik.http.services.dlgServ.loadbalancer.server.port=80"  

volumes:
  postgres_data:

networks:
  proxy:
    external: true
